load_balancer:
    image: tutum/haproxy
    links:
        - web
    ports:
        - "80:8080"

cache:
    image: redis

database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel

web:
    image: andrewmclagan/nginx-hhvm
    links:
        - database
        - cache
    volumes:
        - ./:/var/www
    environment:
        - APP_ENV=production
        - DB_DATABASE=menahousedb
        - DB_PASSWORD=root
- VIRTUAL_HOST=laravel.local
